### ISSUE TITLE
Columns behave like rows [Display: block instead of flex]

### ISSUE THREAD

**Issue by aristizabal95** [ownbee/bootstrap-grid-card#2]
## **Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- **Version:** v0.1.1
- **Browser and Operating System:** Brave, Windows 11 (Browser and OS independent bug)

## **Description of problem:**
I'm not being able to have cards behave like columns. Instead, all cards occupy a whole row, even if they have differing sizes that would fit in the 12-grid system.
This is something I can easily fix if I inspect the elements and add `display: flex` to the `.container-fluid` class.

This behavior is both OS and browser independent. I've tried on both Mac and Windows, with my default browser (Brave -> Chromium) as well as Safari

### Current behavior:
<img src="https://i.imgur.com/vjLQVRN.png"></img>
Elements have the correct size, but they span a whole row.

### Expected behavior:
<img src="https://i.imgur.com/sIT1XbY.png"></img>
Adding `display: flex;` to `.container-fluid` fixes the problem. Of course if I reload this is gone.

This is because `.container-fluid` inherits `display: block;` from the `div` default styles. This disables flex.
<img src="https://i.imgur.com/04UGQjL.png"></img>

## **Additional information:**
I installed this addon through HACS.

My dashboard configuration looks like this:
```yaml
views:
  - title: Home
    panel: true
    cards:
      - type: custom:bootstrap-grid-card
        cards:
          - type: col
            class: col-sm-hidden col-md-3
            cards:
              - type: custom:search-card
          - type: col
            class: col-sm-12 col-md-9
            cards:
              - type: custom:search-card
              - type: entities
                entities:
                  - light.07580048e868e757f421
                  - light.main_light
                  - light.table_lamp
                  - type: custom:slider-entity-row
                    entity: cover.motorized_blinds
                title: Bedroom
                show_header_toggle: false
                state_color: true
```
Am I doing something wrong? 
I'd be happy to help, although I have no experience with lovelace addons. I believe this should be a simple fix.
