### ISSUE TITLE
cols span on multiple rows instead of resizing on the same row.

### ISSUE THREAD

**Issue by jayPare** [ownbee/bootstrap-grid-card#32]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- **Version:** v0.2.2
- **Last working release (if known):** vx.y.z
- **Browser and Operating System:** Chrome, Windows 11

Tested on both Firefox and Chrome latest versions.

**Description of problem:**

I declared a row which includes 2 col, one col-10 and one col-2. In the col-10 col, I have one custom:week-planner-card card and a row card. In the row, I have 7 col cards in which I have  an entities card. I expected the col to span on the same row, but it spans on 2, where the first one has 5 of them, and the 2nd row, 2 of them. Those on the 2nd row are larger.

I could set the class of each col to something like col-1 or col-2. However, the former would not take the full width of the row, leaving a space a col-5 size on the right (12 minus (7 x 1)). The latter would produce 2 row, since 7 col of size 2 is larger than 12.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Here is a small snippet:

```
type: custom:bootstrap-grid-card
class: container-fluid g-0
cards:
  - type: row
    cards:
      - type: col
        class: col-10
        cards:
          - type: custom:week-planner-card
            calendars:
              - entity: calendar.jamessmith_gmail_com
                color: "#e6c229"
            days: 7
            noCardBackground: true
            eventBackground: rgba(0, 0, 0, .75)
            startingDay: sunday
            weather:
              entity: weather.forecast_home
              showTemperature: true
            texts:
              noEvents: No Events
              fullDay: All Day
              today: Today
              sunday: Sunday
              monday: Monday
              tuesday: Tuesday
              wednesday: Wednesday
              thursday: Thursday
              friday: Friday
              saturday: Saturday
              tomorrow: Tomorrow
            columns:
              extraLarge: 7
              large: 7
              medium: 7
              small: 7
              extraSmall: 7
          - type: row
            cards:
              - type: col
                class: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                class: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                class: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
              - type: col
                cards:
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_the_floor
                    title: Jane Doe
                  - type: entities
                    entities:
                      - entity: input_boolean.clean_bathroom
                    title: James Smith
      - type: col
        class: col-2
        cards:
          - type: heading
            heading: Montly Tasks
            heading_style: title
            icon: mdi:calendar-check
          - type: entities
            entities:
              - entity: input_boolean.clean_windows
            title: Jane Doe
          - type: entities
            entities:
              - entity: input_boolean.fill_water_softener
            title: James Smith
column_span: 4
```

Here is also a screeenshot:

![Image](https://github.com/user-attachments/assets/867f7205-51cc-44ea-89c7-4299c1c19383)
