### ISSUE TITLE
Since last version update(0.1.2) my nested layout is broken

### ISSUE THREAD

**Issue by sdrapha** [ownbee/bootstrap-grid-card#5]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- **Version:** v0.1.2
- **Last working release (if known):** v0.1.1
- **Browser and Operating System:** All browsers, All systems

**Description of problem:**

Since last version update, my nested layout broke

Old behavior from previous version: 
![bootstrap-demo](https://user-images.githubusercontent.com/25059996/151577462-6d8e48d5-0403-443a-95dd-58edcdf5c26b.gif)

New behaviour with the latest version:
![bootstrap-demo-2](https://user-images.githubusercontent.com/25059996/151577968-c01dd073-b92c-4566-95f4-3512ab7900d1.gif)

To replicate the issue, that is my card, It can be tested in a card inside a PANEL VIEW, so it takes the whole width of the screen

```yaml
type: custom:bootstrap-grid-card
global_row_class: justify-content-center
cards:
  - type: row
    cards:
      - type: row
        cards:
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:shield
                name: Aarlo
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:cloud
                name: Weather
                type: custom:button-card
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:warehouse
                name: Garage
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:account
                name: Personal
                type: custom:button-card
      - type: row
        cards:
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:television
                name: TV
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:server
                name: Stats
                type: custom:button-card
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:shape-square-plus
                name: Lab
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: var(--primary-color)
                  icon:
                    - color: var(--primary-color)
                icon: mdi:home
                name: Home
                type: custom:button-card
      - type: row
        cards:
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                haptic: light
                icon: mdi:biohazard
                name: Covid
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                haptic: light
                icon: mdi:webcam
                name: Cameras
                type: custom:button-card
          - type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                haptic: light
                icon: mdi:water-pump
                name: Rachio
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                haptic: light
                icon: hass:robot
                name: Automations
                type: custom:button-card

```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ownbee** [comment]
Hmm, I cant find anything that the card has changed to affect this. Bootstrap grid version has changed to between the versions, there might be something in bootstrap itself.

Anyhow, I don't understand what's actually broken. I can see there has been a change in behavior from your imagery but when looking at the layout, the behavior seems reasonable. Can you explain in more detail what's unexpected?

 I just think you need to use the tools in bootstrap to get what you want. I managed to get something very close to your "old behavior" image. The things I changed was:

- Only one row. - You are using a lot of rows which will break the columns.
- Be explicit about how much space each column should take. I used `global_col_class: col-auto` for this test. - You have 2 columns per row which means each column will take up 1/2 container width. Also seems like `custom:button-card` is not centering itself in its container which results in left-aligned button.

```
- type: custom:bootstrap-grid-card
    global_row_class: justify-content-center
    global_col_class: col-auto
    class: "container"
    cards:
      - type: row
        cards:
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:shield
            name: Aarlo
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:cloud
            name: Weather
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:warehouse
            name: Garage
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:account
            name: Personal
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:television
            name: TV
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:server
            name: Stats
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            icon: mdi:shape-square-plus
            name: Lab
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: var(--primary-color)
              icon:
                - color: var(--primary-color)
            icon: mdi:home
            name: Home
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            haptic: light
            icon: mdi:biohazard
            name: Covid
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            haptic: light
            icon: mdi:webcam
            name: Cameras
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            haptic: light
            icon: mdi:water-pump
            name: Rachio
            type: custom:button-card
          - styles:
              card:
                - height: 70px
                - width: 76px
              name:
                - color: null
              icon:
                - color: var(--paper-item-icon-color)
            haptic: light
            icon: hass:robot
            name: Automations
            type: custom:button-card
```

I've also seen that some cards are not very bootstrap compatible since they have styles that aren't very dynamic. I don't know in detail if `custom:button-card` has any problems.

**Comment by sdrapha** [comment]
Thanks for the reply!!!
I won't have time to re-access my aproach and alternatives right know, or investigate further the difference from bootstrap versions, but I will once I have a chance, a couple days from now maybe or next week.

When I first started the card layout( using the old bootstrap version) I did used just one row. 
The problem with that was the buttons were dynamically dropping to the next row one-by-one when there was no space. That didn't looked good. So I ended up doing that nested rows aproach as a way to group buttons, so they break to an extra row in even groups. So it looks nicer, and is easier to find the desired button in a quick glance since, they don't move in order as much.

**Comment by ownbee** [comment]
Aha, I see, you could also try to group your groups with _column_ instead of _row_ to get what you want:

```yaml
     - type: row
        cards:
          - type: col
            # type: row
            cards:
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:television
                name: TV
                type: custom:button-card
              - styles:
                  card:
                    - height: 70px
                    - width: 76px
                  name:
                    - color: null
                  icon:
                    - color: var(--paper-item-icon-color)
                icon: mdi:server
                name: Stats
                type: custom:button-card
```
It could be a bit tricky to use a fixed width in pixels on your buttons and also get even margins since bootstrap is trying to handle the width automatically. I used `col-auto` to tell bootstrap to "fit-content" but I think this is not default behavior. I usually use a percentage value when setting width on things in bootstrap. In your case that would be `width: 50%` (or `size: 50%` as stated in [button-card documentation](https://github.com/custom-cards/button-card#main-options)) if you put your buttons in a col card, but you wont get the fixed pixel size.
