### ISSUE TITLE
Why I can't get a responsive behavior?

### ISSUE THREAD

**Issue by reypm** [ownbee/bootstrap-grid-card#8]
Wonder what I am missing here because my dashboard does not get responsive if I am accessing it from my phone. See the following pic:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/627886/221992032-a317bf5f-0d60-48e8-b9ac-f08c58b91e14.png">

This is the YAML for such view:

```yaml
  - theme: Backend-selected
    title: Office
    path: office
    icon: mdi:chair-rolling
    badges: []
    type: panel
    cards:
      - type: custom:bootstrap-grid-card
        cards:
          - type: row
            class: d-flex flex-row-reverse
            cards:
              - type: custom:mushroom-light-card
                class: col-xs-6 col-md-3 col-xxl-3
                name: Office Light
                entity: light.office
                show_brightness_control: true
                use_light_color: true
                collapsible_controls: true
                fill_container: true
                secondary_info: last-changed
                layout: horizontal
              - type: custom:mushroom-fan-card
                class: col-xs-6 col-md-3 col-xxl-3
                name: Office Fan
                entity: fan.office
                icon_animation: true
                show_percentage_control: true
                collapsible_controls: true
                fill_container: true
                secondary_info: last-changed
                layout: horizontal
```
